# Generated by Django 4.1 on 2023-05-06 10:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("basic_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofileinfo",
            old_name="portfolio_pic",
            new_name="profile_pic",
        ),
    ]
